#!/usr/bin/env python3
"""Sequentially parse the remaining Build Up Your Chess 1 chapters.

This is a resumable offline batch runner. It never seeds book items or changes
Neon: the review report names only diagrams whose board recognition or turn
marker extraction needs a human decision.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import book_board_parser as parser



CHAPTER_RANGES: dict[int, tuple[int, int]] = {
    3: (28, 41), 4: (42, 51), 5: (52, 61), 6: (62, 71),
    7: (72, 79), 8: (80, 89), 9: (90, 97), 10: (98, 107),
    11: (108, 117), 12: (118, 125), 13: (126, 135), 14: (136, 145),
    15: (146, 153), 16: (154, 161), 17: (162, 169), 18: (170, 179),
    19: (180, 189), 20: (190, 199), 21: (200, 209), 22: (210, 219),
    23: (220, 229), 24: (230, 241),
}


def chapter_args(args: argparse.Namespace, chapter: int, first_page: int, last_page: int) -> argparse.Namespace:
    return argparse.Namespace(
        pdf=args.pdf,
        chapter=chapter,
        first_master_page=first_page,
        last_master_page=last_page,
        output=str(Path(args.output_root) / f"chapter-{chapter}"),
        book_page_offset=2,
        diagram_start=1,
        dpi=args.dpi,
        minimum_board_edge=args.minimum_board_edge,
        crop_margin=args.crop_margin,
        recognize=True,
        endpoint=args.endpoint,
        delay_seconds=args.delay_seconds,
        retry_errors=args.retry_errors,
        validate_api=None,
        validate_book_id="build-up-your-chess-1",
        env_file="backend/.env",
    )


def parse_chapter(args: argparse.Namespace, chapter: int, first_page: int, last_page: int) -> list[dict]:
    current = chapter_args(args, chapter, first_page, last_page)
    output = Path(current.output)
    candidates_path = output / "candidates.json"
    records = json.loads(candidates_path.read_text(encoding="utf-8")) if candidates_path.exists() else parser.build_candidates(current)
    parser.write_json(candidates_path, records)
    parser.recognize_records(records, current, output / "recognition-checkpoint.json")
    parser.write_json(output / "positions.json", {"chapter": chapter, "positions": records})
    return records


def issue(record: dict) -> str | None:
    if record.get("recognitionStatus") != "ok":
        return record.get("error", "ChessOCR did not return a valid piece placement")
    if record.get("sideToMove") not in {"w", "b"}:
        return record.get("turnDetection", "side-to-move marker could not be read")
    return None


def write_review_report(path: Path, summaries: list[dict], failures: list[dict]) -> None:
    lines = [
        "# Remaining-book board-parser review",
        "",
        "Generated by `tools/book-board-parser/parse_remaining.py`. This is an offline extraction report; it does not seed or modify book items.",
        "",
        "## Summary",
        "",
        "| Chapter | Detected boards | Recognized boards | Review items |",
        "| --- | ---: | ---: | ---: |",
    ]
    for summary in summaries:
        lines.append(f"| {summary['chapter']} | {summary['detected']} | {summary['recognized']} | {summary['issues']} |")
    lines.extend(["", "## Diagrams requiring review", ""])
    if not failures:
        lines.append("No recognition or side-to-move-marker failures were found.")
    else:
        lines.extend([
            "These are deliberately not corrected by the tool. Inspect the original page and decide the position/turn before creating a study item.",
            "",
            "| Chapter | Diagram | Book page | Master PDF page | Chapter PDF page | Reason |",
            "| --- | --- | ---: | ---: | ---: | --- |",
        ])
        for failure in failures:
            reason = failure["reason"].replace("|", "\\|")
            lines.append(f"| {failure['chapter']} | {failure['diagram']} | {failure['bookPage']} | {failure['masterPDFPage']} | {failure['chapterPDFPage']} | {reason} |")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    cli = argparse.ArgumentParser(description=__doc__)
    cli.add_argument("pdf")
    cli.add_argument("--output-root", default="tools/book-board-parser/work/build-up-your-chess-1")
    cli.add_argument("--report", default="docs/study-from-book/board-parser-errors.md")
    cli.add_argument("--from-chapter", type=int, default=3)
    cli.add_argument("--to-chapter", type=int, default=24)
    cli.add_argument("--dpi", type=int, default=200)
    cli.add_argument("--minimum-board-edge", type=int, default=175)
    cli.add_argument("--crop-margin", type=float, default=0.035)
    cli.add_argument("--endpoint", default=parser.DEFAULT_ENDPOINT)
    cli.add_argument("--delay-seconds", type=float, default=5.2)
    cli.add_argument("--retry-errors", action="store_true")
    args = cli.parse_args()
    if args.delay_seconds < 5:
        cli.error("--delay-seconds must be at least 5 to respect the ChessOCR rate limit")
    requested = [chapter for chapter in sorted(CHAPTER_RANGES) if args.from_chapter <= chapter <= args.to_chapter]
    if not requested:
        cli.error("requested chapter range does not overlap Chapters 3-24")

    summaries: list[dict] = []
    failures: list[dict] = []
    for chapter in requested:
        first_page, last_page = CHAPTER_RANGES[chapter]
        print(f"chapter {chapter}: pages {first_page}-{last_page}", flush=True)
        records = parse_chapter(args, chapter, first_page, last_page)
        chapter_failures = []
        for record in records:
            reason = issue(record)
            if reason:
                chapter_failures.append({
                    "chapter": chapter,
                    "diagram": record["diagram"],
                    "bookPage": record["bookPage"],
                    "masterPDFPage": record["masterPDFPage"],
                    "chapterPDFPage": record["chapterPDFPage"],
                    "reason": reason,
                })
        failures.extend(chapter_failures)
        recognized = sum(record.get("recognitionStatus") == "ok" for record in records)
        summaries.append({"chapter": chapter, "detected": len(records), "recognized": recognized, "issues": len(chapter_failures)})


        write_review_report(Path(args.report), summaries, failures)
        print(f"chapter {chapter}: detected={len(records)} recognized={recognized} review={len(chapter_failures)}", flush=True)

    write_review_report(Path(args.report), summaries, failures)
    print(f"complete: chapters={len(summaries)} detected={sum(item['detected'] for item in summaries)} recognized={sum(item['recognized'] for item in summaries)} review={len(failures)}", flush=True)


if __name__ == "__main__":
    main()
